name: number_trivia
description: Flutter TDD Clean Architecture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  build_runner: ^2.1.7

flutter:

  uses-material-design: true
